INSERT INTO `secteurs` (`id`,`nom_secteur`) VALUES
(1, 'Agriculture, nature, animaux, environnement'),
(2, 'Agro-alimentaire'),
(3, 'Automobile, mécanique, techniciens, ingénieurs'),
(4, 'Commerce'),
(5, 'Construction, second œuvre'),
(6, 'Droit, administration, gouvernement'),
(7, 'Education, recherche, formation'),
(8, 'Emplois administratifs, secrétaires, postes et téléphone'),
(9, 'Encadrement, direction'),
(10, 'Finance, banque, assurance'),
(11, 'Hôtellerie, tourisme, loisirs et sports'),
(12, 'Informatique, télécommunication'),
(13, 'Langues, bibliothèques, archivage, conservation'),
(14, 'Mercatique, relations publiques, publicité'),
(15, 'Média, graphisme, imprimerie, art et création'),
(16, 'Métallurgie, mécanique, production industrielle'),
(17, 'Nettoyage et assainissement'),
(18, 'Pétrole, gaz, mines, production d\'énergie, services publics'),
(19, 'Ressources humaines, relations professionnelles, organisation'),
(20, 'Santé, paramédical, laboratoires'),
(21, 'Sécurité, armée, police'),
(22, 'Transports et logistique'),
(23, 'Travail social, soin à la personne, enfance');

CREATE TABLE `fonctions` (
  `id` bigint(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `secteur_id` bigint(20) UNSIGNED NOT NULL REFERENCES secteurs(id) ON DELETE CASCADE,
  `nom_fonction` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `fonctions` (`id`,`secteur_id`,`nom_fonction`) VALUES
(1,1,'Acheteurs'),
(2,1,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(3,1,'Agriculteurs et ouvriers qualifiés de l’horticulture et des pépinières'),
(4,1,'Agriculteurs et ouvriers qualifiés des cultures et de l’élevage à but commercial'),
(5,1,'Agriculteurs et ouvriers qualifiés, cultures de plein champ'),
(6,1,'Agriculteurs et ouvriers qualifiés, cultures diversifiées'),
(7,1,'Agriculteurs et éleveurs, subsistance'),
(8,1,'Agriculteurs, subsistance'),
(9,1,'Agronomes et assimilés'),
(10,1,'Aides de cuisine'),
(11,1,'Apiculteurs, sériciculteurs et ouvriers qualifiés de l’apiculture et de la sériciculture'),
(12,1,'Aquaculteurs et ouvriers de l’aquaculture'),
(13,1,'Arboriculteurs et ouvriers qualifiés de l’arboriculture'),
(14,1,'Architectes paysagistes'),
(15,1,'Aviculteurs et ouvriers qualifiés de l’aviculture'),
(16,1,'Chasseurs et trappeurs'),
(17,1,'Classeurs et essayeurs de produits (à l’exception des aliments et des boissons)'),
(18,1,'Conducteurs d’engins mobiles agricoles et forestiers'),
(19,1,'Courtiers en marchandises'),
(20,1,'Directeurs et cadres de direction, agriculture et sylviculture'),
(21,1,'Directeurs et cadres de direction, aquaculture et pêche'),
(22,1,'Directeurs et cadres de direction, ressources humaines'),
(23,1,'Directeurs et cadres de direction, services financiers'),
(24,1,'Directeurs et gérants, centres sportifs, centres de loisirs et centres culturels'),
(25,1,'Employés de bureau, fonctions générales'),
(26,1,'Employés du service des stocks'),
(27,1,'Employés, service du personnel'),
(28,1,'Exploitants et ouvriers forestiers'),
(29,1,'Forgerons, estampeurs et conducteurs de presses à forger'),
(30,1,'Fumigateurs et préposés au contrôle de la vermine et des mauvaises herbes'),
(31,1,'Inspecteurs, salubrité de l’environnement et de la santé au travail, et assimilés'),
(32,1,'Instructeurs et animateurs de programmes, loisirs et activités de remise en forme'),
(33,1,'Manœuvres de l’agriculture'),
(34,1,'Manœuvres de l’agriculture et de l’élevage'),
(35,1,'Manœuvres de l’élevage'),
(36,1,'Manœuvres du bâtiment'),
(37,1,'Manœuvres forestiers'),
(38,1,'Manœuvres pêcheurs et aquaculteurs'),
(39,1,'Manœuvres, cultures maraîchères et horticulture'),
(40,1,'Mécaniciens et réparateurs de machines agricoles et industrielles'),
(41,1,'Personnel des services de protection et de sécurité, non classé ailleurs'),
(42,1,'Pompiers'),
(43,1,'Professions intermédiaires de la comptabilité'),
(44,1,'Professions intermédiaires de l’application de la loi et assimilées non classées ailleurs'),
(45,1,'Pêcheurs de la pêche côtière et en eaux intérieures'),
(46,1,'Pêcheurs de la pêche en haute mer'),
(47,1,'Pêcheurs, chasseurs, trappeurs et cueilleurs, subsistance'),
(48,1,'Représentants et techniciens commerciaux'),
(49,1,'Réceptionnistes (fonctions générales)'),
(50,1,'Scaphandriers et plongeurs'),
(51,1,'Secrétaires (fonctions générales)'),
(52,1,'Spécialistes de la publicité et de la commercialisation'),
(53,1,'Spécialistes, ressources humaines et évolution de carrière'),
(54,1,'Techniciens des sciences de la vie (à l’exception de la médecine)'),
(55,1,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(56,1,'Techniciens et assistants vétérinaires'),
(57,1,'Techniciens, agriculture et élevage'),
(58,1,'Techniciens, sylviculture'),
(59,1,'Toiletteurs et gardiens d’animaux'),
(60,1,'Vétérinaires'),
(61,1,'Éleveurs de bétail, subsistance'),
(62,1,'Éleveurs et ouvriers qualifiés de l’élevage commercial et assimilés, non classés ailleurs'),
(63,1,'Éleveurs et ouvriers qualifiés de l’élevage de bétail'),
(64,2,'Acheteurs'),
(65,2,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(66,2,'Aides de cuisine'),
(67,2,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(68,2,'Autres nettoyeurs'),
(69,2,'Bouchers, poissonniers et assimilés'),
(70,2,'Boulangers, pâtissiers et confiseurs'),
(71,2,'Classeurs et essayeurs de produits (à l’exception des aliments et des boissons)'),
(72,2,'Concepteurs modélistes de produits et de vêtements'),
(73,2,'Conducteurs de machines d’emballage, d’embouteillage et d’étiquetage'),
(74,2,'Conducteurs de machines pour la fabrication de denrées alimentaires et de produits connexes'),
(75,2,'Conserveurs de fruits, de légumes et assimilés'),
(76,2,'Cuisiniers, restauration rapide'),
(77,2,'Dégustateurs et classeurs de denrées alimentaires et de boissons'),
(78,2,'Emballeurs à la main et autres manœuvres des industries manufacturières'),
(79,2,'Employés de bureau, fonctions générales'),
(80,2,'Employés du service des stocks'),
(81,2,'Employés, service du personnel'),
(82,2,'Fabricants des produits laitiers'),
(83,2,'Ingénieurs chimistes'),
(84,2,'Métiers qualifiés de la préparation du tabac et de la fabrication des produits du tabac'),
(85,2,'Physiciens et astronomes'),
(86,2,'Professions intermédiaires de la comptabilité'),
(87,2,'Représentants et techniciens commerciaux'),
(88,2,'Réceptionnistes (fonctions générales)'),
(89,2,'Secrétaires (fonctions générales)'),
(90,2,'Spécialistes de la publicité et de la commercialisation'),
(91,2,'Spécialistes, ressources humaines et évolution de carrière'),
(92,2,'Spécialistes, sciences techniques de la production et de l’industrie'),
(93,2,'Techniciens des sciences de la vie (à l’exception de la médecine)'),
(94,2,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(95,2,'Techniciens, contrôle de processus industriels non classés ailleurs'),
(96,3,'Acheteurs'),
(97,3,'Agents de services commerciaux non classés ailleurs'),
(98,3,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(99,3,'Aides de cuisine'),
(100,3,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(101,3,'Chimistes'),
(102,3,'Commerçants, magasins'),
(103,3,'Dessinateurs industriels'),
(104,3,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(105,3,'Directeurs et cadres de direction, ressources humaines'),
(106,3,'Directeurs et cadres de direction, ventes et commercialisation'),
(107,3,'Directeurs généraux d’entreprise'),
(108,3,'Employés de bureau, fonctions générales'),
(109,3,'Employés du service des stocks'),
(110,3,'Employés, service du personnel'),
(111,3,'Encaisseurs de distributeurs automatiques à prépaiement et releveurs de compteurs'),
(112,3,'Ingénieurs chimistes'),
(113,3,'Ingénieurs civils'),
(114,3,'Ingénieurs des mines, ingénieurs métallurgistes et assimilés'),
(115,3,'Ingénieurs mécaniciens'),
(116,3,'Ingénieurs écologistes'),
(117,3,'Ingénieurs électriciens'),
(118,3,'Ingénieurs électroniciens'),
(119,3,'Inspecteurs, salubrité de l’environnement et de la santé au travail, et assimilés'),
(120,3,'Laqueurs, vernisseurs et assimilés'),
(121,3,'Laveurs de véhicules'),
(122,3,'Manutentionnaires'),
(123,3,'Manœuvres du bâtiment'),
(124,3,'Manœuvres, enlèvement des ordures et matériel recyclable'),
(125,3,'Monteurs et réparateurs de lignes électriques'),
(126,3,'Mécaniciens et ajusteurs d’appareils électriques'),
(127,3,'Mécaniciens et réparateurs de machines agricoles et industrielles'),
(128,3,'Mécaniciens et réparateurs de véhicules à moteur'),
(129,3,'Mécaniciens et réparateurs d’appareils électroniques'),
(130,3,'Mécaniciens-installateurs réfrigération et climatisation'),
(131,3,'Météorologues'),
(132,3,'Officiers mécaniciens de navires'),
(133,3,'Physiciens et astronomes'),
(134,3,'Pompistes'),
(135,3,'Professions intermédiaires de la comptabilité'),
(136,3,'Professions intermédiaires de l’application de la loi et assimilées non classées ailleurs'),
(137,3,'Représentants et techniciens commerciaux'),
(138,3,'Réceptionnistes (fonctions générales)'),
(139,3,'Réparateurs de bicyclettes et assimilés'),
(140,3,'Secrétaires (fonctions générales)'),
(141,3,'Sociologues, anthropologues et assimilés'),
(142,3,'Spécialistes de la protection de l’environnement'),
(143,3,'Spécialistes de la publicité et de la commercialisation'),
(144,3,'Spécialistes des relations publiques'),
(145,3,'Spécialistes, ressources humaines et évolution de carrière'),
(146,3,'Spécialistes, sciences techniques de la production et de l’industrie'),
(147,3,'Spécialistes, sciences techniques non classés ailleurs'),
(148,3,'Superviseurs, magasins'),
(149,3,'Tapissiers et assimilés'),
(150,3,'Techniciens de télécommunications'),
(151,3,'Techniciens des mines, techniciens métallurgistes'),
(152,3,'Techniciens des sciences chimiques et physiques'),
(153,3,'Techniciens des sciences physiques et techniques non classés ailleurs'),
(154,3,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(155,3,'Techniciens du génie civil'),
(156,3,'Techniciens en chimie industrielle'),
(157,3,'Techniciens en construction mécanique'),
(158,3,'Techniciens en électricité'),
(159,3,'Techniciens en électronique'),
(160,3,'Tôliers-chaudronniers'),
(161,3,'Vendeurs, magasin'),
(162,3,'Électriciens du bâtiment et assimilés'),
(163,4,'Acheteurs'),
(164,4,'Agents de sécurité'),
(165,4,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(166,4,'Aides de cuisine'),
(167,4,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(168,4,'Bouchers, poissonniers et assimilés'),
(169,4,'Boulangers, pâtissiers et confiseurs'),
(170,4,'Caissiers et billettistes'),
(171,4,'Coiffeurs'),
(172,4,'Commerçants, magasins'),
(173,4,' Concepteurs modélistes de produits et de vêtements'),
(174,4,'Cordonniers et assimilés'),
(175,4,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(176,4,'Directeurs et cadres de direction, publicité et relations publiques'),
(177,4,'Directeurs et cadres de direction, recherche-développement'),
(178,4,' Directeurs et cadres de direction, ressources humaines'),
(179,4,'Directeurs et cadres de direction, ventes et commercialisation'),
(180,4,'Directeurs et gérants, commerce de détail et de gros'),
(181,4,'Directeurs et gérants, services non classés ailleurs'),
(182,4,'Décorateurs et designers d’intérieurs'),
(183,4,'Démonstrateurs en magasin'),
(184,4,'Employés administratifs non classés ailleurs'),
(185,4,'Employés chargés d’informer la clientèle non classés ailleurs'),
(186,4,'Employés de bureau, fonctions générales'),
(187,4,'Employés de centre d’appel'),
(188,4,'Employés du service des stocks'),
(189,4,'Employés, service du personnel'),
(190,4,'Employés, service d’information'),
(191,4,'Esthéticiens et assimilés'),
(192,4,'Garnisseurs de rayons'),
(193,4,'Intervieweurs, enquêtes et études de marché'),
(194,4,'Manœuvres polyvalents'),
(195,4,'Mécaniciens-réparateurs d’instruments de précision'),
(196,4,'Métiers de l’artisanat sur textile, sur cuir et sur des matériaux similaires'),
(197,4,'Pharmaciens'),
(198,4,'Professions intermédiaires de la comptabilité'),
(199,4,'Représentants et techniciens commerciaux'),
(200,4,'Réceptionnistes (fonctions générales)'),
(201,4,'Secrétaires (fonctions générales)'),
(202,4,'Spécialistes de la publicité et de la commercialisation'),
(203,4,'Spécialistes des relations publiques'),
(204,4,'Spécialistes des ventes, secteurs médical et technique (à l’exception des TIC)'),
(205,4,'Spécialistes, ressources humaines et évolution de carrière'),
(206,4,'Superviseurs, magasins'),
(207,4,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(208,4,'Travailleurs des petits métiers des rues et assimilés'),
(209,4,'Télévendeurs'),
(210,4,'Vendeurs ambulants (à l’exception de l’alimentation)'),
(211,4,'Vendeurs ambulants de comestibles'),
(212,4,'Vendeurs au porte-à-porte'),
(213,4,'Vendeurs non classés ailleurs'),
(214,4,'Vendeurs à l’étal et sur les marchés'),
(215,4,'Vendeurs, magasin'),
(216,5,'Acheteurs'),
(217,5,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(218,5,'Agents immobiliers'),
(219,5,'Aides de cuisine'),
(220,5,'Architectes, bâtiment'),
(221,5,'Auteurs et autres écrivains'),
(222,5,'Autres nettoyeurs'),
(223,5,'Boutefeux'),
(224,5,'Cartographes et géomètres'),
(225,5,'Charpentiers en bois et menuisiers du bâtiment'),
(226,5,'Charpentiers métalliers et monteurs de charpentes métalliques'),
(227,5,'Commissaires-priseurs et autres experts en évaluation'),
(228,5,'Conducteurs de grues, d’engins de levage divers et de matériels similaires'),
(229,5,'Conducteurs de machines de blanchisserie'),
(230,5,'Conducteurs de machines et d’installations fixes non classés ailleurs'),
(231,5,'Conducteurs de machines à blanchir, à teindre et à nettoyer les tissus'),
(232,5,'Conducteurs de machines à coudre'),
(233,5,'Conducteurs d’engins de terrassement et de matériels similaires'),
(234,5,'Conducteurs d’incinérateurs et d’installations de traitement de l’eau'),
(235,5,'Conducteurs d’installations de préparation des minerais et de la roche'),
(236,5,'Conducteurs d’installations et de machines de traitement chimique'),
(237,5,'Constructeurs de maisons'),
(238,5,'Constructeurs en béton armé, maçons ragréeurs et assimilés'),
(239,5,'Couseurs, brodeurs et assimilés'),
(240,5,'Couvreurs et zingueurs'),
(241,5,'Dessinateurs industriels'),
(242,5,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(243,5,'Directeurs et cadres de direction, bâtiment'),
(244,5,'Décorateurs et designers d’intérieurs'),
(245,5,'Employés chargés d’informer la clientèle non classés ailleurs'),
(246,5,'Employés de bureau, fonctions générales'),
(247,5,'Employés du service des stocks'),
(248,5,'Employés du service d’ordonnancement de la production'),
(249,5,'Employés, service du personnel'),
(250,5,'Fendeurs et tailleurs de pierre'),
(251,5,'Manœuvres de chantier de travaux publics'),
(252,5,'Manœuvres du bâtiment'),
(253,5,'Manœuvres polyvalents'),
(254,5,'Maçons'),
(255,5,'Monteurs en construction mécanique'),
(256,5,'Monteurs en isolation thermique et acoustique'),
(257,5,'Mécaniciens et ajusteurs d’appareils électriques'),
(258,5,'Mécaniciens et réparateurs de machines agricoles et industrielles'),
(259,5,'Mécaniciens-installateurs réfrigération et climatisation'),
(260,5,'Métiers qualifiés du bâtiment (gros œuvre) et assimilés non classés ailleurs'),
(261,5,'Métiers qualifiés du traitement du bois'),
(262,5,'Peintres en bâtiment et poseurs de papiers peints'),
(263,5,'Plombiers et tuyauteurs'),
(264,5,'Plâtriers'),
(265,5,'Poseurs de revêtements de sol et carreleurs'),
(266,5,'Professions intermédiaires de la comptabilité'),
(267,5,'Prêteurs sur gages et bailleurs de fonds'),
(268,5,'Ravaleurs de façades et ramoneurs'),
(269,5,'Représentants et techniciens commerciaux'),
(270,5,'Réceptionnistes (fonctions générales)'),
(271,5,'Scaphandriers et plongeurs'),
(272,5,'Secrétaires (fonctions générales)'),
(273,5,'Souffleurs, mouleurs, tailleurs, mouleurs et polisseurs de verre'),
(274,5,'Spécialistes de la publicité et de la commercialisation'),
(275,5,'Spécialistes, ressources humaines et évolution de carrière'),
(276,5,'Spécialistes, sciences techniques non classés ailleurs'),
(277,5,'Superviseurs, bâtiment'),
(278,5,'Tapissiers et assimilés'),
(279,5,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(280,5,'Techniciens du génie civil'),
(281,5,'Urbanistes et ingénieurs de la circulation routière'),
(282,5,'Vitriers'),
(283,5,'Ébénistes, menuisiers et assimilés'),
(284,5,'Électriciens du bâtiment et assimilés'),
(285,6,'Acheteurs'),
(286,6,'Agents des services publics accordant des permis et des licences'),
(287,6,'Agents des services publics accordant des prestations sociales'),
(288,6,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(289,6,'Aides de cuisine'),
(290,6,'Avocats'),
(291,6,'Cadres supérieurs de l’administration publique'),
(292,6,'Chefs traditionnels et chefs de village'),
(293,6,'Classeurs et essayeurs de produits (à l’exception des aliments et des boissons)'),
(294,6,'Contrôleurs des impôts'),
(295,6,'Directeurs des services administratifs non classés ailleurs'),
(296,6,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(297,6,'Dirigeants et cadres supérieurs d’organisations spécialisées'),
(298,6,'Employés de bureau, fonctions générales'),
(299,6,'Employés de services statistiques ou financiers'),
(300,6,'Employés du service des stocks'),
(301,6,'Employés, service du personnel'),
(302,6,'Inspecteurs des douanes et des frontières'),
(303,6,'Inspecteurs, salubrité de l’environnement et de la santé au travail, et assimilés'),
(304,6,'Juristes non classés ailleurs'),
(305,6,'Magistrats'),
(306,6,'Membres des corps législatifs'),
(307,6,'Philosophes, historiens et spécialistes des sciences politiques'),
(308,6,'Professeurs d’université et d’établissements d’enseignement supérieur'),
(309,6,'Professions intermédiaires de la comptabilité'),
(310,6,'Professions intermédiaires de l’application de la loi et assimilées non classées ailleurs'),
(311,6,'Professions juridiques intermédiaires et assimilées'),
(312,6,'Réceptionnistes (fonctions générales)'),
(313,6,'Secrétaires (fonctions générales)'),
(314,6,'Sociologues, anthropologues et assimilés'),
(315,6,'Spécialistes des relations publiques'),
(316,6,'Spécialistes, administration et politiques'),
(317,6,'Spécialistes, ressources humaines et évolution de carrière'),
(318,6,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(319,7,'Acheteurs'),
(320,7,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(321,7,'Aides de cuisine'),
(322,7,'Aides-enseignants'),
(323,7,'Autres professeurs de disciplines artistiques'),
(324,7,'Autres professeurs de langues'),
(325,7,'Autres professeurs de musique'),
(326,7,'Cadres de direction, éducation'),
(327,7,'Contrôleurs des impôts'),
(328,7,'Employés de bureau, fonctions générales'),
(329,7,'Employés de services statistiques ou financiers'),
(330,7,'Employés du service des stocks'),
(331,7,'Employés, service du personnel'),
(332,7,'Enseignants, éducation spécialisée'),
(333,7,'Formateurs en technologies de l’information'),
(334,7,'Instituteurs, enseignement primaire'),
(335,7,'Instructeurs et animateurs de programmes, loisirs et activités de remise en forme'),
(336,7,'Intervieweurs, enquêtes et études de marché'),
(337,7,'Mathématiciens, actuaires et statisticiens'),
(338,7,'Moniteurs d’auto-école'),
(339,7,'Philosophes, historiens et spécialistes des sciences politiques'),
(340,7,'Professeurs d’université et d’établissements d’enseignement supérieur'),
(341,7,'Professeurs, enseignement secondaire'),
(342,7,'Professeurs, enseignement technique et professionnel'),
(343,7,'Professions intermédiaires de la comptabilité'),
(344,7,'Professions intermédiaires de la statistique, des mathématiques et assimilées'),
(345,7,'Représentants et techniciens commerciaux'),
(346,7,'Réceptionnistes (fonctions générales)'),
(347,7,'Secrétaires (fonctions générales)'),
(348,7,'Spécialistes de la publicité et de la commercialisation'),
(349,7,'Spécialistes de l’enseignement, non classés ailleurs'),
(350,7,'Spécialistes des méthodes d’enseignement'),
(351,7,'Spécialistes, ressources humaines et évolution de carrière'),
(352,7,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(353,7,'Éducateurs de la petite enfance'),
(354,8,'Acheteurs'),
(355,8,'Aides comptables et teneurs de livres'),
(356,8,'Aides de cuisine'),
(357,8,'Caissiers et billettistes'),
(358,8,'Classeurs-archivistes'),
(359,8,'Codeurs, correcteurs d’épreuves et assimilés'),
(360,8,'Commis, service de paie'),
(361,8,'Dactylographes et opérateurs de traitement de texte'),
(362,8,'Directeurs des services administratifs non classés ailleurs'),
(363,8,'Directeurs et cadres de direction, ressources humaines'),
(364,8,'Directeurs et gérants, services non classés ailleurs'),
(365,8,'Employés chargés d’informer la clientèle non classés ailleurs'),
(366,8,'Employés de bureau, fonctions générales'),
(367,8,'Employés de centre d’appel'),
(368,8,'Employés de service du courrier'),
(369,8,'Employés de services statistiques ou financiers'),
(370,8,'Employés du service des stocks'),
(371,8,'Employés du service d’ordonnancement de la production'),
(372,8,'Employés, service du personnel'),
(373,8,'Employés, service d’information'),
(374,8,'Encaisseurs et assimilés'),
(375,8,' Guichetiers de banque et assimilés'),
(376,8,'Intervieweurs, enquêtes et études de marché'),
(377,8,'Messagers, porteurs de bagages et livreurs de colis'),
(378,8,'Opérateurs sur clavier numérique'),
(379,8,' Professions intermédiaires de la comptabilité'),
(380,8,'Représentants et techniciens commerciaux'),
(381,8,'Réceptionnistes (fonctions générales)'),
(382,8,'Secrétaires (fonctions générales)'),
(383,8,'Secrétaires d’administration et secrétaires exécutifs'),
(384,8,'Secrétaires médicales/médicaux'),
(385,8,'Secrétaires, services juridiques'),
(386,8,'Spécialistes de la publicité et de la commercialisation'),
(387,8,'Spécialistes, ressources humaines et évolution de carrière'),
(388,8,'Superviseurs, travail de bureau'),
(389,8,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(390,8,'Travailleurs des petits métiers des rues et assimilés'),
(391,8,'Téléphonistes-standardistes'),
(392,8,'Télévendeurs'),
(393,8,'Vendeurs, magasin'),
(394,8,'Écrivains publics et assimilés'),
(395,9,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(396,9,'Cadres de direction, garde d’enfants'),
(397,9,'Cadres de direction, services aux personnes âgées'),
(398,9,'Cadres de direction, services de santé'),
(399,9,'Cadres de direction, services sociaux'),
(400,9,'Cadres de direction, éducation'),
(401,9,'Cadres supérieurs de l’administration publique'),
(402,9,'Commerçants, magasins'),
(403,9,'Cuisiniers'),
(404,9,'Directeurs des services administratifs non classés ailleurs'),
(405,9,'Directeurs et cadres de direction, agriculture et sylviculture'),
(406,9,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(407,9,'Directeurs et cadres de direction, aquaculture et pêche'),
(408,9,'Directeurs et cadres de direction, bâtiment'),
(409,9,'Directeurs et cadres de direction, industrie manufacturière'),
(410,9,'Directeurs et cadres de direction, mines'),
(411,9,'Directeurs et cadres de direction, publicité et relations publiques'),
(412,9,'Directeurs et cadres de direction, recherche-développement'),
(413,9,'Directeurs et cadres de direction, ressources humaines'),
(414,9,'Directeurs et cadres de direction, services financiers'),
(415,9,'Directeurs et cadres de direction, stratégie et planifications'),
(416,9,'Directeurs et cadres de direction, succursales de banque, services financiers et assurances'),
(417,9,'Directeurs et cadres de direction, technologies de l’information et des communications'),
(418,9,'Directeurs et cadres de direction, ventes et commercialisation'),
(419,9,'Directeurs et gérants, centres sportifs, centres de loisirs et centres culturels'),
(420,9,'Directeurs et gérants, commerce de détail et de gros'),
(421,9,'Directeurs et gérants, hôtellerie'),
(422,9,'Directeurs et gérants, restauration'),
(423,9,'Directeurs et gérants, services non classés ailleurs'),
(424,9,'Directeurs généraux d’entreprise'),
(425,9,'Membres des corps législatifs'),
(426,9,'Pharmaciens'),
(427,9,'Superviseurs, bâtiment'),
(428,9,'Superviseurs, mines'),
(429,10,'Acheteurs'),
(430,10,'Agents de services commerciaux non classés ailleurs'),
(431,10,'Agents d’assurances'),
(432,10,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(433,10,'Agents immobiliers'),
(434,10,'Aides comptables et teneurs de livres'),
(435,10,'Aides de cuisine'),
(436,10,'Analystes financiers'),
(437,10,'Cadres comptables'),
(438,10,'Commissaires-priseurs et autres experts en évaluation'),
(439,10,'Conseillers en finances et investissements'),
(440,10,'Contrôleurs des impôts'),
(441,10,'Courtiers en marchandises'),
(442,10,'Courtiers en valeurs et cambistes'),
(443,10,'Directeurs et cadres de direction, publicité et relations publiques'),
(444,10,'Directeurs et cadres de direction, ressources humaines'),
(445,10,'Directeurs et cadres de direction, services financiers'),
(446,10,'Directeurs et cadres de direction, succursales de banque, services financiers et assurances'),
(447,10,'Employés de bureau, fonctions générales'),
(448,10,'Employés de services statistiques ou financiers'),
(449,10,'Employés du service des stocks'),
(450,10,'Employés, service du personnel'),
(451,10,'Encaisseurs et assimilés'),
(452,10,'Guichetiers de banque et assimilés'),
(453,10,'Mathématiciens, actuaires et statisticiens'),
(454,10,'Professions intermédiaires de la comptabilité'),
(455,10,'Professions intermédiaires de la statistique, des mathématiques et assimilées'),
(456,10,'Prêteurs sur gages et bailleurs de fonds'),
(457,10,'Représentants et techniciens commerciaux'),
(458,10,'Responsables des prêts'),
(459,10,'Réceptionnistes (fonctions générales)'),
(460,10,'Secrétaires (fonctions générales)'),
(461,10,'Spécialistes de la publicité et de la commercialisation'),
(462,10,'Spécialistes des bases de données et des réseaux d’ordinateurs non classés ailleurs'),
(463,10,'Spécialistes des relations publiques'),
(464,10,'Spécialistes du travail social'),
(465,10,'Spécialistes, ressources humaines et évolution de carrière'),
(466,10,'Superviseurs, travail de bureau'),
(467,10,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(468,10,'Urbanistes et ingénieurs de la circulation routière'),
(469,10,'Économistes'),
(470,11,'Acheteurs'),
(471,11,'Agents de sécurité'),
(472,11,'Agents d’emploi et de recrutement de main-d\'œuvre'),
(473,11,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(474,11,'Agriculteurs et ouvriers qualifiés de l’horticulture et des pépinières'),
(475,11,'Aides de cuisine'),
(476,11,'Annonceurs-présentateurs de radio, de télévision et autres médias'),
(477,11,'Artistes créateurs et exécutants non classés ailleurs'),
(478,11,'Astrologues, diseurs de bonne aventure et assimilés'),
(479,11,'Athlètes et sportifs de compétition'),
(480,11,'Autres professions intermédiaires de la culture et de la création artistique'),
(481,11,'Barmen'),
(482,11,'Boulangers, pâtissiers et confiseurs'),
(483,11,'Chefs cuisiniers'),
(484,11,'Commis au comptoir, restauration rapide'),
(485,11,'Concepteurs graphiques, multimédia – graphistes'),
(486,11,'Consultants et employés d’agence de voyages'),
(487,11,'Croupiers et assimilés dans le secteur des jeux de hasard'),
(488,11,'Cuisiniers'),
(489,11,'Cuisiniers, restauration rapide'),
(490,11,'Directeurs des services administratifs non classés ailleurs'),
(491,11,'Directeurs et gérants, centres sportifs, centres de loisirs et centres culturels'),
(492,11,'Directeurs et gérants, hôtellerie'),
(493,11,'Directeurs et gérants, restauration'),
(494,11,'Directeurs et gérants, services non classés ailleurs'),
(495,11,'Employés de bureau, fonctions générales'),
(496,11,'Employés du service des stocks'),
(497,11,'Employés, service du personnel'),
(498,11,'Entraîneurs sportifs et arbitres de sport'),
(499,11,'Esthéticiens et assimilés'),
(500,11,'Guides'),
(501,11,'Instructeurs et animateurs de programmes, loisirs et activités de remise en forme'),
(502,11,'Messagers, porteurs de bagages et livreurs de colis'),
(503,11,'Metteurs en scène de cinéma, de théâtre et d’autres spectacles'),
(504,11,'Organisateurs de conférences et d’événements'),
(505,11,'Personnel de compagnie et valets de chambre'),
(506,11,'Personnel des services directs aux particuliers, non classé ailleurs'),
(507,11,'Professions intermédiaires de la comptabilité'),
(508,11,'Professions élémentaires non classées ailleurs'),
(509,11,'Représentants et techniciens commerciaux'),
(510,11,'Réceptionnistes (fonctions générales)'),
(511,11,'Réceptionnistes, hôtellerie'),
(512,11,'Secrétaires (fonctions générales)'),
(513,11,'Serveurs'),
(514,11,'Spécialistes de la publicité et de la commercialisation'),
(515,11,'Spécialistes, ressources humaines et évolution de carrière'),
(516,11,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(517,12,'Acheteurs'),
(518,12,'Administrateurs de systèmes'),
(519,12,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(520,12,'Aides de cuisine'),
(521,12,'Analystes de systèmes'),
(522,12,'Concepteurs de logiciels'),
(523,12,'Concepteurs de sites internet et de multimédia'),
(524,12,'Concepteurs et analystes de logiciels, et concepteurs de multimédia non classés ailleurs'),
(525,12,'Concepteurs graphiques, multimédia – graphistes'),
(526,12,'Directeurs et cadres de direction, technologies de l’information et des communications'),
(527,12,'Employés de bureau, fonctions générales'),
(528,12,'Employés du service des stocks'),
(529,12,'Employés, service du personnel'),
(530,12,'Formateurs en technologies de l’information'),
(531,12,'Journalistes'),
(532,12,'Monteurs et réparateurs, technologies de l’information et des communications'),
(533,12,'Professions intermédiaires de la comptabilité'),
(534,12,'Programmeurs d’applications'),
(535,12,'Représentants et techniciens commerciaux'),
(536,12,'Réceptionnistes (fonctions générales)'),
(537,12,'Secrétaires (fonctions générales)'),
(538,12,'Spécialistes de la publicité et de la commercialisation'),
(539,12,'Spécialistes des bases de données'),
(540,12,'Spécialistes des réseaux d’ordinateurs'),
(541,12,'Spécialistes des télécommunications'),
(542,12,'Spécialistes des ventes, des technologies de l’information et des communications'),
(543,12,'Spécialistes, ressources humaines et évolution de carrière'),
(544,12,'Techniciens de l’internet'),
(545,12,'Techniciens de télécommunications'),
(546,12,'Techniciens des technologies de l’information et des communications, opérations'),
(547,12,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(548,12,'Techniciens, réseaux et systèmes d’ordinateurs'),
(549,13,'Acheteurs'),
(550,13,'Agents de sécurité'),
(551,13,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(552,13,'Aides de cuisine'),
(553,13,'Archivistes paléographes et conservateurs de musée'),
(554,13,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(555,13,'Bibliothécaires, documentalistes et professions assimilées'),
(556,13,'Employés de bibliothèque'),
(557,13,'Employés de bureau, fonctions générales'),
(558,13,'Employés du service des stocks'),
(559,13,'Employés, service du personnel'),
(560,13,'Guides'),
(561,13,'Philosophes, historiens et spécialistes des sciences politiques'),
(562,13,'Professions intermédiaires de la comptabilité'),
(563,13,'Représentants et techniciens commerciaux'),
(564,13,'Réceptionnistes (fonctions générales)'),
(565,13,'Secrétaires (fonctions générales)'),
(566,13,'Sociologues, anthropologues et assimilés'),
(567,13,'Spécialistes de la publicité et de la commercialisation'),
(568,13,'Spécialistes, ressources humaines et évolution de carrière'),
(569,13,'Techniciens de galeries d’art, de musées et de bibliothèques'),
(570,13,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(571,13,'Traducteurs, interprètes et linguistes'),
(572,14,'Acheteurs'),
(573,14,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(574,14,'Aides de cuisine'),
(575,14,'Directeurs et cadres de direction, publicité et relations publiques'),
(576,14,'Directeurs et cadres de direction, ventes et commercialisation'),
(577,14,'Employés administratifs non classés ailleurs'),
(578,14,'Employés de bureau, fonctions générales'),
(579,14,'Employés du service des stocks'),
(580,14,'Employés, service du personnel'),
(581,14,'Intervieweurs, enquêtes et études de marché'),
(582,14,'Mathématiciens, actuaires et statisticiens'),
(583,14,'Photographes'),
(584,14,'Professeurs d’université et d’établissements d’enseignement supérieur'),
(585,14,'Professions intermédiaires de la comptabilité'),
(586,14,'Représentants et techniciens commerciaux'),
(587,14,'Réceptionnistes (fonctions générales)'),
(588,14,'Secrétaires (fonctions générales)'),
(589,14,'Spécialistes de la publicité et de la commercialisation'),
(590,14,'Spécialistes des relations publiques'),
(591,14,'Spécialistes, ressources humaines et évolution de carrière'),
(592,14,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(593,14,'Économistes'),
(594,15,'Acheteurs'),
(595,15,'Acteurs'),
(596,15,'Agents d’emploi et de recrutement de main-d\'œuvre'),
(597,15,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(598,15,'Aides de cuisine'),
(599,15,'Annonceurs-présentateurs de radio, de télévision et autres médias'),
(600,15,'Artistes plasticiens'),
(601,15,'Auteurs et autres écrivains'),
(602,15,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(603,15,'Autres professions intermédiaires de la culture et de la création artistique'),
(604,15,'Codeurs, correcteurs d’épreuves et assimilés'),
(605,15,'Compositeurs et préparateurs en forme imprimante et assimilés'),
(606,15,'Compositeurs, musiciens et chanteurs'),
(607,15,'Concepteurs de sites internet et de multimédia'),
(608,15,'Concepteurs graphiques, multimédia – graphistes'),
(609,15,'Concepteurs modélistes de produits et de vêtements'),
(610,15,'Couseurs, brodeurs et assimilés'),
(611,15,'Danseurs et chorégraphes'),
(612,15,'Directeurs et cadres de direction, publicité et relations publiques'),
(613,15,'Directeurs et gérants, centres sportifs, centres de loisirs et centres culturels'),
(614,15,'Décorateurs et designers d’intérieurs'),
(615,15,'Employés de bureau, fonctions générales'),
(616,15,'Employés du service des stocks'),
(617,15,'Employés du service d’ordonnancement de la production'),
(618,15,'Employés, service du personnel'),
(619,15,'Facteurs et accordeurs d’instruments de musique'),
(620,15,'Imprimeurs'),
(621,15,'Journalistes'),
(622,15,'Mannequins et autres modèles'),
(623,15,'Manutentionnaires'),
(624,15,'Metteurs en scène de cinéma, de théâtre et d’autres spectacles'),
(625,15,'Mécaniciens-réparateurs d’instruments de précision'),
(626,15,'Métiers de l’artisanat sur textile, sur cuir et sur des matériaux similaires'),
(627,15,'Métiers qualifiés de l’industrie et de l’artisanat non classés ailleurs'),
(628,15,'Peintres d’enseignes, peintres-décorateurs et graveurs'),
(629,15,'Photographes'),
(630,15,'Professions intermédiaires de la comptabilité'),
(631,15,'Professions élémentaires non classées ailleurs'),
(632,15,'Relieurs et assimilés'),
(633,15,'Représentants et techniciens commerciaux'),
(634,15,'Réceptionnistes (fonctions générales)'),
(635,15,'Secrétaires (fonctions générales)'),
(636,15,'Spécialistes de la publicité et de la commercialisation'),
(637,15,'Spécialistes des relations publiques'),
(638,15,'Spécialistes, ressources humaines et évolution de carrière'),
(639,15,'Spécialistes, sciences techniques de la production et de l’industrie'),
(640,15,'Tailleurs, couturiers, fourreurs, modistes et chapeliers'),
(641,15,'Techniciens de radiotélévision et d’enregistrement audiovisuel'),
(642,15,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(643,15,'Techniciens d’appareils électromédicaux'),
(644,15,'Travailleurs des petits métiers des rues et assimilés'),
(645,15,'Vendeurs non classés ailleurs'),
(646,15,'Ébénistes, menuisiers et assimilés'),
(647,15,'Électriciens du bâtiment et assimilés'),
(648,16,'Acheteurs'),
(649,16,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(650,16,'Aides de cuisine'),
(651,16,'Auteurs et autres écrivains'),
(652,16,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(653,16,'Autres nettoyeurs'),
(654,16,'Biologistes, botanistes, zoologistes et assimilés'),
(655,16,'Charpentiers en bois et menuisiers du bâtiment'),
(656,16,'Charpentiers métalliers et monteurs de charpentes métalliques'),
(657,16,'Chauffeurs de machines à vapeur et de chaudières'),
(658,16,'Chimistes'),
(659,16,'Classeurs et essayeurs de produits (à l’exception des aliments et des boissons)'),
(660,16,'Concepteurs modélistes de produits et de vêtements'),
(661,16,'Conducteurs de machines de blanchisserie'),
(662,16,'Conducteurs de machines de papeterie'),
(663,16,'Conducteurs de machines et d’installations fixes non classés ailleurs'),
(664,16,'Conducteurs de machines pour la fabrication de produits en matières plastiques'),
(665,16,'Conducteurs de machines pour la fabrication de produits textiles et d’articles en fourrure et en cuir'),
(666,16,'Conducteurs de machines pour la fabrication des chaussures et assimilés'),
(667,16,'Conducteurs de machines pour la fabrication des produits en caoutchouc'),
(668,16,'Conducteurs de machines pour la fabrication des produits photographiques'),
(669,16,'Conducteurs de machines à blanchir, à teindre et à nettoyer les tissus'),
(670,16,'Conducteurs de machines à coudre'),
(671,16,'Conducteurs de machines à fabriquer du ciment, de la pierre et d’autres produits minéraux'),
(672,16,'Conducteurs de machines à préparer les fibres, à filer et à bobiner'),
(673,16,'Conducteurs de machines à préparer les fourrures et le cuir'),
(674,16,'Conducteurs de métiers mécaniques à tisser et à tricoter'),
(675,16,'Conducteurs d’installations de raffinage de pétrole et de gaz naturel'),
(676,16,'Conducteurs d’installations de traitement chimique'),
(677,16,'Conducteurs d’installations de traitement superficiel des métaux'),
(678,16,'Conducteurs d’installations de transformation et de traitement des métaux'),
(679,16,'Conducteurs d’installations de verrerie et de céramique'),
(680,16,'Conducteurs d’installations et de machines de traitement chimique'),
(681,16,'Conducteurs d’installations pour la fabrication du papier et de la pâte à papier'),
(682,16,'Conducteurs d’installations pour le travail du bois'),
(683,16,'Contrôleurs des processus industriels, métallurgie'),
(684,16,'Cordonniers et assimilés'),
(685,16,'Couseurs, brodeurs et assimilés'),
(686,16,'Dessinateurs industriels'),
(687,16,'Directeurs et cadres de direction, industrie manufacturière'),
(688,16,'Directeurs généraux d’entreprise'),
(689,16,'Employés de bureau, fonctions générales'),
(690,16,'Employés du service des stocks'),
(691,16,'Employés du service d’ordonnancement de la production'),
(692,16,'Employés, service du personnel'),
(693,16,'Forgerons, estampeurs et conducteurs de presses à forger'),
(694,16,'Gréeurs et épisseurs de câbles'),
(695,16,'Géologues et géophysiciens'),
(696,16,'Imprimeurs'),
(697,16,'Ingénieurs mécaniciens'),
(698,16,'Inspecteurs, salubrité de l’environnement et de la santé au travail, et assimilés'),
(699,16,'Joailliers et orfèvres'),
(700,16,'Laqueurs, vernisseurs et assimilés'),
(701,16,'Manœuvres des industries manufacturières non classés ailleurs'),
(702,16,'Monteurs d’appareils électriques et électroniques'),
(703,16,'Monteurs en construction mécanique'),
(704,16,'Monteurs et assembleurs non classés ailleurs'),
(705,16,'Mouleurs et noyauteurs de fonderie'),
(706,16,'Mouleurs, polisseurs et affûteurs'),
(707,16,'Mécaniciens et ajusteurs d’appareils électriques'),
(708,16,'Mécaniciens et réparateurs de machines agricoles et industrielles'),
(709,16,'Mécaniciens et réparateurs de moteurs d’avion'),
(710,16,'Mécaniciens et réparateurs de véhicules à moteur'),
(711,16,'Mécaniciens et réparateurs d’appareils électroniques'),
(712,16,'Mécaniciens-réparateurs d’instruments de précision'),
(713,16,'Métiers de l’artisanat non classés ailleurs'),
(714,16,'Métiers de l’artisanat sur bois et sur des matériaux similaires'),
(715,16,'Métiers de l’artisanat sur textile, sur cuir et sur des matériaux similaires'),
(716,16,'Métiers qualifiés de la coupe de vêtements et assimilés'),
(717,16,'Outilleurs et assimilés'),
(718,16,'Peintres d’enseignes, peintres-décorateurs et graveurs'),
(719,16,'Peintres en bâtiment et poseurs de papiers peints'),
(720,16,'Pharmaciens'),
(721,16,'Physiciens et astronomes'),
(722,16,'Plombiers et tuyauteurs'),
(723,16,'Potiers et assimilés (produits céramiques et abrasifs)'),
(724,16,'Professions intermédiaires de la comptabilité'),
(725,16,'Représentants et techniciens commerciaux'),
(726,16,'Réceptionnistes (fonctions générales)'),
(727,16,'Régleurs et conducteurs de machines à bois'),
(728,16,'Régleurs et conducteurs de machines-outils'),
(729,16,'Secrétaires (fonctions générales)'),
(730,16,'Soudeurs et oxycoupeurs'),
(731,16,'Souffleurs, mouleurs, tailleurs, mouleurs et polisseurs de verre'),
(732,16,'Spécialistes de la publicité et de la commercialisation'),
(733,16,'Spécialistes des ventes, secteurs médical et technique (à l’exception des TIC)'),
(734,16,'Spécialistes, ressources humaines et évolution de carrière'),
(735,16,'Superviseurs, industries manufacturières'),
(736,16,'Tailleurs, couturiers, fourreurs, modistes et chapeliers'),
(737,16,'Tanneurs, peaussiers et mégissiers'),
(738,16,'Tapissiers et assimilés'),
(739,16,'Techniciens de prothèses médicales et dentaires'),
(740,16,'Techniciens de radiotélévision et d’enregistrement audiovisuel'),
(741,16,'Techniciens des mines, techniciens métallurgistes'),
(742,16,'Techniciens des sciences de la vie (à l’exception de la médecine)'),
(743,16,'Techniciens des sciences physiques et techniques non classés ailleurs'),
(744,16,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(745,16,'Techniciens en chimie industrielle'),
(746,16,'Techniciens en électronique'),
(747,16,'Techniciens, contrôle de processus industriels non classés ailleurs'),
(748,16,'Tôliers-chaudronniers'),
(749,17,'Acheteurs'),
(750,17,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(751,17,'Aides de cuisine'),
(752,17,'Aides de ménage à domicile'),
(753,17,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(754,17,'Autres nettoyeurs'),
(755,17,'Balayeurs et manœuvres assimilés'),
(756,17,'Concierges'),
(757,17,'Conducteurs d’incinérateurs et d’installations de traitement de l’eau'),
(758,17,'Directeurs des services administratifs non classés ailleurs'),
(759,17,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(760,17,'Directeurs et cadres de direction, ressources humaines'),
(761,17,'Directeurs et cadres de direction, ventes et commercialisation'),
(762,17,'Employés de bureau, fonctions générales'),
(763,17,'Employés du service des stocks'),
(764,17,'Employés, service du personnel'),
(765,17,'Gouvernantes et intendants à domicile'),
(766,17,'Intendants et superviseurs des services de nettoyage de bureaux, des hôtels et d’autres établissements'),
(767,17,'Laveurs de vitres'),
(768,17,'Laveurs de véhicules'),
(769,17,'Laveurs et repasseurs de linge à la main'),
(770,17,'Manœuvres polyvalents'),
(771,17,'Manœuvres, enlèvement des ordures et matériel recyclable'),
(772,17,'Professions intermédiaires de la comptabilité'),
(773,17,'Ravaleurs de façades et ramoneurs'),
(774,17,'Représentants et techniciens commerciaux'),
(775,17,'Réceptionnistes (fonctions générales)'),
(776,17,'Secrétaires (fonctions générales)'),
(777,17,'Spécialistes de la publicité et de la commercialisation'),
(778,17,'Spécialistes des relations publiques'),
(779,17,'Spécialistes, ressources humaines et évolution de carrière'),
(780,17,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(781,17,'Trieurs de déchets'),
(782,18,'Acheteurs'),
(783,18,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(784,18,'Aides de cuisine'),
(785,18,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(786,18,'Autres nettoyeurs'),
(787,18,'Chimistes'),
(788,18,'Classeurs et essayeurs de produits (à l’exception des aliments et des boissons)'),
(789,18,'Conducteurs de grues, d’engins de levage divers et de matériels similaires'),
(790,18,'Conducteurs de machines et d’installations fixes non classés ailleurs'),
(791,18,'Conducteurs de poids lourds et de camions'),
(792,18,'Conducteurs d’engins de terrassement et de matériels similaires'),
(793,18,'Conducteurs d’incinérateurs et d’installations de traitement de l’eau'),
(794,18,'Conducteurs d’installations de production d’énergie'),
(795,18,'Conducteurs d’installations de préparation des minerais et de la roche'),
(796,18,'Conducteurs d’installations de raffinage de pétrole et de gaz naturel'),
(797,18,'Courtiers en marchandises'),
(798,18,'Dessinateurs industriels'),
(799,18,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(800,18,'Directeurs et cadres de direction, mines'),
(801,18,'Employés de bureau, fonctions générales'),
(802,18,'Employés du service des stocks'),
(803,18,'Employés du service d’ordonnancement de la production'),
(804,18,'Employés, service du personnel'),
(805,18,'Encaisseurs de distributeurs automatiques à prépaiement et releveurs de compteurs'),
(806,18,'Foreurs, sondeurs de puits et assimilés'),
(807,18,'Géologues et géophysiciens'),
(808,18,'Ingénieurs des mines, ingénieurs métallurgistes et assimilés'),
(809,18,'Inspecteurs, salubrité de l’environnement et de la santé au travail, et assimilés'),
(810,18,'Manœuvres des mines et des carrières'),
(811,18,'Mathématiciens, actuaires et statisticiens'),
(812,18,'Mineurs et conducteurs d’installations de mine'),
(813,18,'Monteurs et réparateurs de lignes électriques'),
(814,18,'Mécaniciens et ajusteurs d’appareils électriques'),
(815,18,'Mécaniciens et réparateurs de machines agricoles et industrielles'),
(816,18,'Physiciens et astronomes'),
(817,18,'Plombiers et tuyauteurs'),
(818,18,'Professions intermédiaires de la comptabilité'),
(819,18,'Représentants et techniciens commerciaux'),
(820,18,'Réceptionnistes (fonctions générales)'),
(821,18,'Régleurs et conducteurs de machines à bois'),
(822,18,'Régleurs et conducteurs de machines-outils'),
(823,18,'Secrétaires (fonctions générales)'),
(824,18,'Spécialistes de la publicité et de la commercialisation'),
(825,18,'Spécialistes, ressources humaines et évolution de carrière'),
(826,18,'Superviseurs, magasins'),
(827,18,'Superviseurs, mines'),
(828,18,'Techniciens des mines, techniciens métallurgistes'),
(829,18,'Techniciens des sciences de la vie (à l’exception de la médecine)'),
(830,18,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(831,18,'Techniciens en électricité'),
(832,19,'Acheteurs'),
(833,19,'Agents d’emploi et de recrutement de main-d\'œuvre'),
(834,19,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(835,19,'Aides de cuisine'),
(836,19,'Analystes, gestion et organisation'),
(837,19,'Directeurs et cadres de direction, ressources humaines'),
(838,19,'Employés de bureau, fonctions générales'),
(839,19,'Employés du service des stocks'),
(840,19,'Employés, service du personnel'),
(841,19,'Inspecteurs, salubrité de l’environnement et de la santé au travail, et assimilés'),
(842,19,'Professions intermédiaires de la comptabilité'),
(843,19,'Psychologues'),
(844,19,'Représentants et techniciens commerciaux'),
(845,19,'Réceptionnistes (fonctions générales)'),
(846,19,'Secrétaires (fonctions générales)'),
(847,19,'Spécialistes de la formation du personnel'),
(848,19,'Spécialistes de la publicité et de la commercialisation'),
(849,19,'Spécialistes, ressources humaines et évolution de carrière'),
(850,19,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(851,20,'Acheteurs'),
(852,20,'Agents de santé communautaire'),
(853,20,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(854,20,'Aides de cuisine'),
(855,20,'Aides-soignants en institution'),
(856,20,'Ambulanciers'),
(857,20,'Assistants et thérapeutes en médecine dentaire'),
(858,20,'Assistants médicaux'),
(859,20,'Audiologistes et orthophonistes'),
(860,20,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(861,20,'Autres nettoyeurs'),
(862,20,'Biologistes, botanistes, zoologistes et assimilés'),
(863,20,'Cadres de direction, services de santé'),
(864,20,'Cadres infirmiers'),
(865,20,'Chauffeurs de taxi et conducteurs d’automobiles et de camionnettes'),
(866,20,'Chimistes'),
(867,20,'Conducteurs d’installations de traitement chimique'),
(868,20,'Dentistes'),
(869,20,'Directeurs et cadres de direction, publicité et relations publiques'),
(870,20,'Directeurs et cadres de direction, ressources humaines'),
(871,20,'Diététiciens et spécialistes de la nutrition'),
(872,20,'Employés de bureau, fonctions générales'),
(873,20,'Employés du service des stocks'),
(874,20,'Employés, service du personnel'),
(875,20,'Mathématiciens, actuaires et statisticiens'),
(876,20,'Médecins généralistes'),
(877,20,'Médecins spécialistes'),
(878,20,'Opticiens'),
(879,20,'Optométristes'),
(880,20,'Personnel infirmier (niveau intermédiaire)'),
(881,20,'Personnel soignant et assimilé, non classé ailleurs'),
(882,20,'Pharmaciens'),
(883,20,'Physiciens et astronomes'),
(884,20,'Physiothérapeutes'),
(885,20,'Praticiens des médecines traditionnelles et des médecines complémentaires'),
(886,20,'Praticiens paramédicaux'),
(887,20,'Professeurs d’université et d’établissements d’enseignement supérieur'),
(888,20,'Professions intermédiaires de la comptabilité'),
(889,20,'Professions intermédiaires de la santé non classées ailleurs'),
(890,20,'Professions intermédiaires des religions'),
(891,20,'Représentants et techniciens commerciaux'),
(892,20,'Réceptionnistes (fonctions générales)'),
(893,20,'Secrétaires (fonctions générales)'),
(894,20,'Secrétaires médicales/médicaux'),
(895,20,'Sociologues, anthropologues et assimilés'),
(896,20,'Spécialistes de la publicité et de la commercialisation'),
(897,20,'Spécialistes de la salubrité de l’environnement, de l’hygiène et de la santé au travail'),
(898,20,'Spécialistes de la santé non classés ailleurs'),
(899,20,'Spécialistes des médecines traditionnelles et des médecines complémentaires'),
(900,20,'Spécialistes des relations publiques'),
(901,20,'Spécialistes, ressources humaines et évolution de carrière'),
(902,20,'Superviseurs, industries manufacturières'),
(903,20,'Techniciens de dossiers médicaux'),
(904,20,'Techniciens de laboratoire médical'),
(905,20,'Techniciens de prothèses médicales et dentaires'),
(906,20,'Techniciens des sciences de la vie (à l’exception de la médecine)'),
(907,20,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(908,20,'Techniciens d’appareils électromédicaux'),
(909,20,'Techniciens et assistants en physiothérapie'),
(910,20,'Techniciens et assistants pharmaciens et préparateurs en pharmacie'),
(911,20,'Téléphonistes-standardistes'),
(912,21,'Acheteurs'),
(913,21,'Agents de police'),
(914,21,'Agents de sécurité'),
(915,21,'Agents d’accueil et stewards'),
(916,21,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(917,21,'Aides de cuisine'),
(918,21,'Autres cadres de direction, services spécialisés non classés ailleurs'),
(919,21,'Autres membres des forces armées'),
(920,21,'Concierges'),
(921,21,'Contrôleurs et receveurs de transports publics'),
(922,21,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(923,21,'Directeurs et cadres de direction, publicité et relations publiques'),
(924,21,'Directeurs et cadres de direction, ressources humaines'),
(925,21,'Employés de bureau, fonctions générales'),
(926,21,'Employés du service des stocks'),
(927,21,'Employés, service du personnel'),
(928,21,'Gardiens de prison'),
(929,21,'Inspecteurs des douanes et des frontières'),
(930,21,'Inspecteurs et enquêteurs de police'),
(931,21,'Officiers des forces armées'),
(932,21,'Personnel des services de protection et de sécurité, non classé ailleurs'),
(933,21,'Personnel des services directs aux particuliers, non classé ailleurs'),
(934,21,'Personnel soignant et assimilé, non classé ailleurs'),
(935,21,'Pompiers'),
(936,21,'Pompistes'),
(937,21,'Professions intermédiaires de la comptabilité'),
(938,21,'Professions élémentaires non classées ailleurs'),
(939,21,'Représentants et techniciens commerciaux'),
(940,21,'Réceptionnistes (fonctions générales)'),
(941,21,'Scaphandriers et plongeurs'),
(942,21,'Secrétaires (fonctions générales)'),
(943,21,'Sous-officiers des forces armées'),
(944,21,'Spécialistes de la publicité et de la commercialisation'),
(945,21,'Spécialistes des relations publiques'),
(946,21,'Spécialistes, ressources humaines et évolution de carrière'),
(947,21,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(948,21,'Techniciens du génie civil'),
(949,22,'Acheteurs'),
(950,22,'Agents concessionnaires'),
(951,22,'Agents de police'),
(952,22,'Agents d’accueil et stewards'),
(953,22,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(954,22,'Aides de cuisine'),
(955,22,'Chauffeurs de machines à vapeur et de chaudières'),
(956,22,'Chauffeurs de taxi et conducteurs d’automobiles et de camionnettes'),
(957,22,'Conducteurs de chariots élévateurs'),
(958,22,'Conducteurs de grues, d’engins de levage divers et de matériels similaires'),
(959,22,'Conducteurs de locomotives'),
(960,22,'Conducteurs de machines et d’installations fixes non classés ailleurs'),
(961,22,'Conducteurs de motocycles'),
(962,22,'Conducteurs de poids lourds et de camions'),
(963,22,'Conducteurs de véhicules et de machines à traction animale'),
(964,22,'Conducteurs de véhicules à bras et à pédales'),
(965,22,'Conducteurs d’autobus et de tramways'),
(966,22,'Conducteurs d’engins de terrassement et de matériels similaires'),
(967,22,'Contrôleurs de la circulation aérienne'),
(968,22,'Contrôleurs et receveurs de transports publics'),
(969,22,'Directeurs et cadres de direction, approvisionnement, distribution et assimilés'),
(970,22,'Employés de bureau, fonctions générales'),
(971,22,'Employés du service des stocks'),
(972,22,'Employés du service des transports'),
(973,22,'Employés du service d’ordonnancement de la production'),
(974,22,'Employés, service du personnel'),
(975,22,'Laveurs de véhicules'),
(976,22,'Manutentionnaires'),
(977,22,'Matelots de pont et assimilés'),
(978,22,'Messagers, porteurs de bagages et livreurs de colis'),
(979,22,'Mécaniciens et ajusteurs d’appareils électriques'),
(980,22,'Mécaniciens et réparateurs de machines agricoles et industrielles'),
(981,22,'Mécaniciens et réparateurs de moteurs d’avion'),
(982,22,'Officiers de pont et pilotes'),
(983,22,'Pilotes d’avions et assimilés'),
(984,22,'Professions intermédiaires de la comptabilité'),
(985,22,'Professions intermédiaires de l’application de la loi et assimilées non classées ailleurs'),
(986,22,'Représentants et techniciens commerciaux'),
(987,22,'Réceptionnistes (fonctions générales)'),
(988,22,'Secrétaires (fonctions générales)'),
(989,22,'Serre-freins, aiguilleurs et agents de manœuvre'),
(990,22,'Spécialistes de la publicité et de la commercialisation'),
(991,22,'Spécialistes, ressources humaines et évolution de carrière'),
(992,22,'Techniciens de la sécurité aérienne'),
(993,22,'Techniciens de radiotélévision et d’enregistrement audiovisuel'),
(994,22,'Techniciens de télécommunications'),
(995,22,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(996,22,'Techniciens en construction mécanique'),
(997,22,'Techniciens, contrôle de processus industriels non classés ailleurs'),
(998,22,'Urbanistes et ingénieurs de la circulation routière'),
(999,23,'Acheteurs'),
(1000,23,'Agents de pompes funèbres et embaumeurs'),
(1001,23,'Agents de santé communautaire'),
(1002,23,'Agents d’entretien dans les bureaux, les hôtels et autres établissements'),
(1003,23,'Aides de cuisine'),
(1004,23,'Aides-enseignants'),
(1005,23,'Aides-soignants en institution'),
(1006,23,'Aides-soignants à domicile'),
(1007,23,'Audiologistes et orthophonistes'),
(1008,23,'Cadres de direction, garde d’enfants'),
(1009,23,'Cadres de direction, services aux personnes âgées'),
(1010,23,'Cadres de direction, services de santé'),
(1011,23,'Cadres de direction, services sociaux'),
(1012,23,'Concierges'),
(1013,23,'Directeurs et cadres de direction, ressources humaines'),
(1014,23,'Directeurs et cadres de direction, services financiers'),
(1015,23,'Directeurs et gérants, centres sportifs, centres de loisirs et centres culturels'),
(1016,23,'Diététiciens et spécialistes de la nutrition'),
(1017,23,'Employés de bureau, fonctions générales'),
(1018,23,'Employés du service des stocks'),
(1019,23,'Employés, service du personnel'),
(1020,23,'Gardes d’enfants'),
(1021,23,'Instructeurs et animateurs de programmes, loisirs et activités de remise en forme'),
(1022,23,'Manutentionnaires'),
(1023,23,'Ministres des cultes'),
(1024,23,'Personnel des services directs aux particuliers, non classé ailleurs'),
(1025,23,'Personnel soignant et assimilé, non classé ailleurs'),
(1026,23,'Physiothérapeutes'),
(1027,23,'Professions intermédiaires de la comptabilité'),
(1028,23,'Professions intermédiaires des religions'),
(1029,23,'Professions intermédiaires du travail social'),
(1030,23,'Psychologues'),
(1031,23,'Représentants et techniciens commerciaux'),
(1032,23,'Réceptionnistes (fonctions générales)'),
(1033,23,'Sages-femmes'),
(1034,23,'Sages-femmes (niveau intermédiaire)'),
(1035,23,'Secrétaires (fonctions générales)'),
(1036,23,'Spécialistes de la publicité et de la commercialisation'),
(1037,23,'Spécialistes de la santé non classés ailleurs'),
(1038,23,'Spécialistes de l’enseignement, non classés ailleurs'),
(1039,23,'Spécialistes du travail social'),
(1040,23,'Spécialistes, ressources humaines et évolution de carrière'),
(1041,23,'Techniciens des technologies de l’information et des communications, soutien aux utilisateurs'),
(1042,23,'Techniciens et assistants en physiothérapie'),
(1043,23,'Éducateurs de la petite enfance');
